package main

import "math/rand"
import "time"
import "strings"

var Names = [...] string {
"Mallory        ",
"Kayla          ",
"Catherine      ",
"Kobe           ",
"Nyasia         ",
"Luz            ",
"Tristen        ",
"Valentino      ",
"Cannon         ",
"Addison        ",
"Kieran         ",
"Madeline       ",
"Arturo         ",
"Michelle       ",
"Lyla           ",
"Shelby         ",
"Karson         ",
"Devin          ",
"Brenna         ",
"Emilie         ",
"Elliot         ",
"Jenna          ",
"Davion         ",
"Kayden         ",
"Zariah         ",
"Kareem         ",
"Quinton        ",
"Cayden         ",
"Alvaro         ",
"Lexi           ",
"Joshua         ",
"Raegan         ",
"Kaelyn         ",
"Daniel         ",
"Teagan         ",
"Maggie         ",
"Zaire          ",
"Cheyanne       ",
"Salma          ",
"Lance          ",
"Daisy          ",
"Dayami         ",
"Nick           ",
"Lila           ",
"Erik           ",
"Kadence        ",
"Michaela       ",
"Braxton        ",
"Dahlia         ",
"Asia           ",
"Alexa          ",
"Yesenia        ",
"Gael           ",
"Donovan        ",
"Tanya          ",
"Aden           ",
"Payton         ",
"Alexis         ",
"Emmy           ",
"Hillary        ",
"Maci           ",
"Isla           ",
"Mia            ",
"Hamza          ",
"Austin         ",
"Callum         ",
"Aditya         ",
"Shiloh         ",
"Sawyer         ",
"Payten         ",
"Camila         ",
"Byron          ",
"Harley         ",
"Emelia         ",
"Kameron        ",
"Paris          ",
"Presley        ",
"Erin           ",
"Theresa        ",
"Lexie          ",
"Van            ",
"Moises         ",
"Raul           ",
"Dane           ",
"Stephen        ",
"Jayden         ",
"Brian          ",
"Antwan         ",
"Joel           ",
"Larissa        ",
"Tony           ",
"Timothy        ",
"Jadiel         ",
"Julianna       ",
"Lailah         ",
"Jaydin         ",
"Ashly          ",
"Noemi          ",
"Karissa        ",
"Dereon			",
}

var Surnames = [...]string {
	"Garner			",
"Hartman        ",
"Ritter         ",
"Mclaughlin     ",
"Conley         ",
"Gibson         ",
"Newman         ",
"Bonilla        ",
"Duffy          ",
"Wolf           ",
"Hanson         ",
"Salinas        ",
"Montoya        ",
"Dominguez      ",
"Ayala          ",
"Crawford       ",
"Proctor        ",
"Adams          ",
"Patton         ",
"Hampton        ",
"Travis         ",
"Chaney         ",
"Shepherd       ",
"Aguilar        ",
"Moon           ",
"Leblanc        ",
"Booker         ",
"Drake          ",
"Jarvis         ",
"Maldonado      ",
"Mcdonald       ",
"Miller         ",
"Lynn           ",
"Melendez       ",
"Gardner        ",
"Porter         ",
"Olsen          ",
"Rocha          ",
"Ward           ",
"Mccullough     ",
"Boyle          ",
"Moody          ",
"Lopez          ",
"Clark          ",
"Armstrong      ",
"Ho             ",
"Austin         ",
"Mack           ",
"Mahoney        ",
"Kramer         ",
"Barker         ",
"Michael        ",
"Jennings       ",
"Mcclure        ",
"Dixon          ",
"Case           ",
"Mann           ",
"Walter         ",
"Anderson       ",
"Henderson      ",
"Peterson       ",
"Wilson         ",
"Baker          ",
"Stuart         ",
"Knox           ",
"Buchanan       ",
"Rivers         ",
"Dorsey         ",
"Bradley        ",
"Copeland       ",
"Hamilton       ",
"Wang           ",
"Dillon         ",
"Bishop         ",
"Dalton         ",
"Rowe           ",
"Ballard        ",
"Freeman        ",
"Wright         ",
"Todd           ",
"Hernandez      ",
"Shah           ",
"Luna           ",
"Nielsen        ",
"Koch           ",
"Wyatt          ",
"Bean           ",
"Washington     ",
"Pitts          ",
"Powell         ",
"Parsons        ",
"Durham         ",
"Howard         ",
"Eaton          ",
"Maynard        ",
"Pace           ",
"Arnold         ",
"Dudley         ",
"Whitaker       ",
"Fernandez      ",
}

var minRandomDate = time.Date(1950, time.January, 1, 23, 0, 0, 0, time.UTC)
var maxRandomDate = time.Date(2000, time.January, 1, 23, 0, 0, 0, time.UTC)

func InitRandom() {
	rand.Seed(time.Now().UnixNano(),)
}
func genRandomName() string {
	name := strings.TrimSpace(Names[rand.Intn(len(Names))])
	surname := strings.TrimSpace(Surnames[rand.Intn(len(Surnames))])
	
	return (name + " " + surname)
}

func genRandomBirthday() string {
	timeFromMin := rand.Int63n(maxRandomDate.Unix() - minRandomDate.Unix())
	birthday := time.Unix(timeFromMin + minRandomDate.Unix(), 0)
	return birthday.Format("2006-01-02")
}

func GenRandomCrewMember() CrewMember {
	newMember := CrewMember{}
	newMember.Name 		= genRandomName()
	newMember.Birthday	= genRandomBirthday()
	newMember.JobID		= rand.Intn(256)
	newMember.Summary	= "No note yet\n Add something\n"
	newMember.Cabin 	= rand.Intn(256)
	return newMember
}
